import type { CandidateInput, SlateGame } from "./types";

export const DEMO_WEEK = {
  season: 2026,
  week: 3,
  label: "Week 3 demo model",
  date: "2026-09-27",
};

export const demoGames: SlateGame[] = [
  { id: "2026_03_BAL_CLE", season: 2026, week: 3, date: DEMO_WEEK.date, time: "1:00 PM", timeWindow: "1 PM", awayTeam: "BAL", homeTeam: "CLE", venue: "Huntington Bank Field", roof: "outdoors", temperature: 67, windMph: 8, spread: -2.5, total: 43.5, status: "scheduled", source: "demo" },
  { id: "2026_03_MIA_BUF", season: 2026, week: 3, date: DEMO_WEEK.date, time: "1:00 PM", timeWindow: "1 PM", awayTeam: "MIA", homeTeam: "BUF", venue: "Highmark Stadium", roof: "outdoors", temperature: 61, windMph: 11, spread: -6.5, total: 49.5, status: "scheduled", source: "demo" },
  { id: "2026_03_TB_ATL", season: 2026, week: 3, date: DEMO_WEEK.date, time: "1:00 PM", timeWindow: "1 PM", awayTeam: "TB", homeTeam: "ATL", venue: "Mercedes-Benz Stadium", roof: "closed", spread: -1.5, total: 47, status: "scheduled", source: "demo" },
  { id: "2026_03_DAL_NYG", season: 2026, week: 3, date: DEMO_WEEK.date, time: "4:05 PM", timeWindow: "4 PM", awayTeam: "DAL", homeTeam: "NYG", venue: "MetLife Stadium", roof: "outdoors", temperature: 72, windMph: 6, spread: 3, total: 46.5, status: "scheduled", source: "demo" },
  { id: "2026_03_GB_CHI", season: 2026, week: 3, date: DEMO_WEEK.date, time: "4:25 PM", timeWindow: "4 PM", awayTeam: "GB", homeTeam: "CHI", venue: "Soldier Field", roof: "outdoors", temperature: 58, windMph: 17, spread: 2.5, total: 44.5, status: "scheduled", source: "demo" },
  { id: "2026_03_SF_SEA", season: 2026, week: 3, date: DEMO_WEEK.date, time: "4:25 PM", timeWindow: "4 PM", awayTeam: "SF", homeTeam: "SEA", venue: "Lumen Field", roof: "outdoors", temperature: 64, windMph: 4, spread: 4, total: 48, status: "scheduled", source: "demo" },
];

export const demoCandidates: CandidateInput[] = [
  {
    id: "bal-cle-spread", gameId: "2026_03_BAL_CLE", matchup: "BAL @ CLE", time: "1:00 PM", timeWindow: "1 PM", market: "ATS",
    bet: "Baltimore -2.5", sportsbookLine: "-2.5", americanOdds: -110, openingLine: "-1.5", currentLine: "-2.5", fairLine: "-4.1",
    estimatedProbability: 0.594, expertAgreement: 0.78, expertSampleAdjustedScore: 0.72, marketSignal: 0.76, contextSignal: 0.66, modelStrength: 0.82,
    modelSummary: "Early-down EPA, pressure rate, and trench grades make Baltimore 4.1-point favorites.",
    expertSummary: "Four of five tracked ATS experts agree; reliability weighting trims raw consensus to 76%.",
    marketSummary: "The line moved through -2 without a public-bet spike, consistent with respected support.",
    contextSummary: "No major offensive-line downgrade; weather is neutral.",
    trend: [-1.5, -2, -2, -2.5, -2.5], historical: { record: "31–18–2", roi: 11.8, sample: 51, clv: 0.72 },
  },
  {
    id: "gb-chi-under", gameId: "2026_03_GB_CHI", matchup: "GB @ CHI", time: "4:25 PM", timeWindow: "4 PM", market: "TOTAL",
    bet: "Under 44.5", sportsbookLine: "44.5", americanOdds: -108, openingLine: "46", currentLine: "44.5", fairLine: "42.8",
    estimatedProbability: 0.572, expertAgreement: 0.72, expertSampleAdjustedScore: 0.68, marketSignal: 0.81, contextSignal: 0.78, modelStrength: 0.77,
    modelSummary: "Situation-neutral pace and explosive-play suppression produce a fair total of 42.8.",
    expertSummary: "Totals specialists lean under after sample-size adjustment.",
    marketSummary: "The total fell 1.5 points while reported ticket share remained balanced.",
    contextSummary: "Forecast calls for 17 mph winds; no indoor contingency.",
    trend: [46, 45.5, 45, 44.5, 44.5], historical: { record: "22–13–1", roi: 9.6, sample: 36, clv: 0.61 },
  },
  {
    id: "dal-nyg-lamb-prop", gameId: "2026_03_DAL_NYG", matchup: "DAL @ NYG", time: "4:05 PM", timeWindow: "4 PM", market: "PROP",
    bet: "C. Lamb 7+ receptions", sportsbookLine: "7+ receptions", americanOdds: 105, openingLine: "+110", currentLine: "+105", fairLine: "61.2%",
    estimatedProbability: 0.612, expertAgreement: 0.67, expertSampleAdjustedScore: 0.65, marketSignal: 0.61, contextSignal: 0.72, modelStrength: 0.79,
    modelSummary: "A 96% route share and 29% target share create the strongest opportunity floor on the slate.",
    expertSummary: "Prop specialists agree on receptions rather than yardage.",
    marketSummary: "The alternate price shortened modestly without crossing a key threshold.",
    contextSummary: "No snap limitation is reported; projected game script favors attempts.",
    trend: [110, 110, 105, 105, 105], historical: { record: "28–19", roi: 8.4, sample: 47, clv: 0.38 },
  },
  {
    id: "mia-buf-ml", gameId: "2026_03_MIA_BUF", matchup: "MIA @ BUF", time: "1:00 PM", timeWindow: "1 PM", market: "MONEYLINE",
    bet: "Buffalo moneyline", sportsbookLine: "-260", americanOdds: -260, openingLine: "-245", currentLine: "-260", fairLine: "-295",
    estimatedProbability: 0.753, expertAgreement: 0.73, expertSampleAdjustedScore: 0.7, marketSignal: 0.67, contextSignal: 0.7, modelStrength: 0.8,
    modelSummary: "Buffalo wins 75.3% of simulations, but the price leaves only a narrow value margin.",
    expertSummary: "Win-probability agreement is high; few experts endorse the price.",
    marketSummary: "Favorite tax increased from -245 to -260 with matched ticket and money share.",
    contextSummary: "Rest and travel favor Buffalo; no quarterback change.",
    trend: [-245, -250, -255, -260, -260], historical: { record: "19–8", roi: 5.2, sample: 27, clv: 0.29 },
  },
  {
    id: "tb-atl-over", gameId: "2026_03_TB_ATL", matchup: "TB @ ATL", time: "1:00 PM", timeWindow: "1 PM", market: "TOTAL",
    bet: "Over 47", sportsbookLine: "47", americanOdds: -110, openingLine: "46.5", currentLine: "47", fairLine: "49.1",
    estimatedProbability: 0.568, expertAgreement: 0.61, expertSampleAdjustedScore: 0.64, marketSignal: 0.58, contextSignal: 0.65, modelStrength: 0.74,
    modelSummary: "Both offenses rank above the demo baseline in pace, red-zone efficiency, and explosive pass rate.",
    expertSummary: "Moderate agreement among tracked totals specialists.",
    marketSummary: "A half-point rise supports the position, though 47 remains a resistance point.",
    contextSummary: "Closed roof removes weather variance; primary skill players project active.",
    trend: [46.5, 46.5, 47, 47, 47], historical: { record: "17–12–1", roi: 6.1, sample: 30, clv: 0.41 },
  },
  {
    id: "sf-sea-purdy-prop", gameId: "2026_03_SF_SEA", matchup: "SF @ SEA", time: "4:25 PM", timeWindow: "4 PM", market: "PROP",
    bet: "B. Purdy over 1.5 pass TDs", sportsbookLine: "1.5", americanOdds: 115, openingLine: "+120", currentLine: "+115", fairLine: "52.8%",
    estimatedProbability: 0.528, expertAgreement: 0.58, expertSampleAdjustedScore: 0.61, marketSignal: 0.56, contextSignal: 0.59, modelStrength: 0.67,
    modelSummary: "Red-zone pass tendency supports the over, but projected attempt volume is only average.",
    expertSummary: "Thin tracked sample and mixed prop-specialist agreement.",
    marketSummary: "Price shortened slightly with no corroborating limit move.",
    contextSummary: "Receiving corps projects intact; divisional familiarity adds uncertainty.",
    trend: [120, 120, 115, 115, 115], historical: { record: "11–10", roi: 1.4, sample: 21, clv: 0.12 },
  },
  {
    id: "sf-sea-spread-conflict", gameId: "2026_03_SF_SEA", matchup: "SF @ SEA", time: "4:25 PM", timeWindow: "4 PM", market: "ATS",
    bet: "Seattle +4", sportsbookLine: "+4", americanOdds: -110, openingLine: "+3", currentLine: "+4", fairLine: "+2.2",
    estimatedProbability: 0.558, expertAgreement: 0.64, expertSampleAdjustedScore: 0.62, marketSignal: 0.31, contextSignal: 0.58, modelStrength: 0.72,
    modelSummary: "The model prices the home underdog at +2.2 and values the extra point.",
    expertSummary: "Modest agreement, concentrated among smaller tracked samples.",
    marketSummary: "The market moved against Seattle from +3 to +4 despite a majority of reported money on the home side.",
    contextSummary: "No major late downgrade, but offensive-line availability is unsettled.",
    trend: [3, 3.5, 3.5, 4, 4], historical: { record: "13–12–1", roi: -0.8, sample: 26, clv: -0.14 },
  },
  {
    id: "dal-nyg-ml-pass", gameId: "2026_03_DAL_NYG", matchup: "DAL @ NYG", time: "4:05 PM", timeWindow: "4 PM", market: "MONEYLINE",
    bet: "Dallas moneyline", sportsbookLine: "-155", americanOdds: -155, openingLine: "-145", currentLine: "-155", fairLine: "-154",
    estimatedProbability: 0.607, expertAgreement: 0.69, expertSampleAdjustedScore: 0.67, marketSignal: 0.6, contextSignal: 0.62, modelStrength: 0.68,
    modelSummary: "Dallas is more likely to win, but its 60.7% estimate is already fully reflected by the price.",
    expertSummary: "Experts favor Dallas outright without identifying moneyline value.",
    marketSummary: "The move from -145 to -155 erased the model’s opening edge.",
    contextSummary: "No context change creates a new pricing advantage.",
    trend: [-145, -150, -150, -155, -155], historical: { record: "14–9", roi: 2.1, sample: 23, clv: 0.08 },
  },
];
